### ISSUE TITLE
Transfer to version 4.15: roadmap

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/size-analysis#13]
The general question is whether our results over 4.13.3 generalize to a deep notification as occured for 4.15 kernel.

We have dataset here: https://gitlab.com/FAMILIAR-project/tuxml-size-analysis-datasets
We have insights about tiny config 4.13.3 vs 4.15 (see #4).

Now we can address a couple of questions 
 - [ ] can we transfer prediction model of 4.13.3 to 4.15? (eg is it "just" prediction of 4.13.3 *plus* 5Mb?) 
 - [ ] are influential options the same? 
 - [ ] what is the accuracy of learning algorithms? 
 - [ ] do we need to perform additional measurements and perhaps more controlled experiments? (like reusing/shifting configs of 4.13.3?)

**Comment by FAMILIAR-project** [comment]
I've a working implementation: `feature_importance415.ipynb` 
We can play with the data and algorithms!

**Comment by dekpro** [comment]
okay, I will play with it asap, I have to finish a draft proposal I need to send it to Cécile by the weekend, and I will attack this
